// Assignment Code
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

//character arrays in global memory
var special = [
  "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "+", "-", ".", "/", ":", ";", "<", "=", ">", "?", "[", "]", "_", "{", "}", "|", "~"
]
var numeric = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9
]
var uppercase = [
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"
]
var lowercase = [
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
]
var arrays = [
  special, numeric, uppercase, lowercase
]

//responsible for the entire functionality of the generate password button
function generatePassword() {
  //prompts, alerts, and confirms to capture user input
  var charNumber = prompt("How many characters would you like to use in your password?");
    
  if (charNumber < 8){
      alert("You must use at least 8 characters.");
      return ("Please try again");
    } else if (charNumber > 128) {
      alert("You must use 128 characters or less");
      return ("Please try again");
    } else {
      
      var userSpecial = confirm("Would you like to use special characters in your password?");
      var userNumeric = confirm("Would you like to use numbers in your password?")
      var userUppercase = confirm("would you like to use uppercase letters in your password?")
      var userLowercase = confirm("Would you like to use lowercase letters in your password?")
      // empty array to store the characters generated by the function.
      var newArray = []

      // select which characters to use, and run a function that only uses the selected characters. At least one type of character must be selected.
      if (userSpecial && userNumeric && userUppercase && userLowercase) {
          // generates password when all types of characters are selected.
          for (var i = 0; i < charNumber; i++) {
            var randomArray = arrays[Math.floor(Math.random () * arrays.length)]; 
            var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
            newArray.push(randomCharacter);
          }     
        userPassword = newArray.join("");
        return userPassword;
      } 
      
      else if ((userSpecial) && (userNumeric === false && userUppercase === false && userLowercase === false)) {
        // generates password with only special characters.
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = special[Math.floor(Math.random () * special.length)];
          newArray.push(randomCharacter);
        }
      userPassword = newArray.join("");
      return userPassword;
      }

      else if ((userNumeric) && (userSpecial === false && userUppercase === false && userLowercase === false)) {
        // generates password with only numbers.
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = numeric[Math.floor(Math.random () * numeric.length)];
          newArray.push(randomCharacter);
        }
      userPassword = newArray.join("");
      return userPassword;
      }

      else if ((userUppercase) && (userNumeric === false && userSpecial === false && userLowercase === false)) {
        // generates password with only uppercase letters.
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = uppercase[Math.floor(Math.random () * uppercase.length)];
          newArray.push(randomCharacter);
        }
      userPassword = newArray.join("");
      return userPassword;
      }

      else if ((userLowercase) && (userNumeric === false && userUppercase === false && userSpecial === false)) {
        // generates password with only lowercase letters.
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = lowercase[Math.floor(Math.random () * lowercase.length)];
          newArray.push(randomCharacter);
        }
      userPassword = newArray.join("");
      return userPassword;
      }

      else if ((userSpecial && userNumeric) && (userUppercase === false && userLowercase === false)) {
        // generates password with special characters and numbers.
        randomArray = special.concat(numeric);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userSpecial && userUppercase) && (userNumeric === false && userLowercase === false)) {
        // generates password with special characters and uppercase letters.
        randomArray = special.concat(uppercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userSpecial && userLowercase) && (userNumeric === false && userUppercase === false)) {
        // generates password with special characters and lowercase letters.
        randomArray = special.concat(lowercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userNumeric && userUppercase) && (userSpecial === false && userLowercase === false)){
        // generates password with numbers and uppercase letters.
        randomArray = numeric.concat(uppercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userNumeric && userLowercase) && (userSpecial === false && userUppercase === false)){
        // generates password with numbers and lowercase letters.
        randomArray = numeric.concat(lowercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userUppercase && userLowercase) && (userSpecial === false && userNumeric === false)) {
        // generates password with uppercase and lowercase letters.
        randomArray = uppercase.concat(lowercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userSpecial && userNumeric && userUppercase) && (userLowercase === false)) {
        // generates password with all characters except lowercase letters.
        randomArray = special.concat(numeric, uppercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userSpecial && userNumeric && userLowercase) && (userUppercase === false)) {
        // generates password with all characters except uppercase letters.
        randomArray = special.concat(numeric, lowercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userSpecial && userUppercase && userLowercase) && (userNumeric === false)) {
        // generates password with all characters except numbers.
        randomArray = special.concat(uppercase, lowercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }

      else if ((userUppercase && userNumeric && userLowercase) && (userSpecial === false)) {
        // generates password with all characters except special characters.
        randomArray = uppercase.concat(numeric, lowercase);
        for (var i = 0; i < charNumber; i++) {
          var randomCharacter = randomArray[Math.floor(Math.random () * randomArray.length)];
          newArray.push(randomCharacter)
        }
        userPassword = newArray.join("");
        return userPassword;
      }
      
      else {
        // if no characters are selected.
        alert("You must select at least one type of character.");
        return ("Please try again");
      }
    }
}
